name: Artifact Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create sample file
        run: |
          mkdir output
          echo "This is your first artifact!" > output/hello.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-first-artifact
          path: output/
